import type { Metadata } from "next";
import "./globals.css";
import {Qwitcher_Grypen,Poppins} from "next/font/google"
import BottomNavbar from "./component/BottomNavbar";


const roboto_init=Qwitcher_Grypen({
  subsets:["latin"],
  weight:['400',],
  variable:'--font-roboto'
})
const Poppins_init=Poppins({
  subsets:["latin"],
  weight:['400',],
  variable:'--font-Poppins'
})
export const metadata: Metadata = {
  title: "Collage Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        {children}
        <BottomNavbar />
      </body>
    </html>
  )
}
