import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/component/Navbar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div>
        <AppRouterCacheProvider>
        {/* <Navbar /> */}
        {children}
        </AppRouterCacheProvider>
        </div>
    </html>
  )
}
